export const cameraIcons = {
  flashImg: require('../assets/picture/flashOn.png'),
  flashOffImg: require('../assets/picture/flashOff.png'),
  dispatchPhotoImg: require('../assets/picture/dispatchPhoto.png'),
  flipCameraImg: require('../assets/picture/flipCamera.png'),
  scannerImg: require('../assets/picture/scanner.png'),
  startRecording: require('../assets/picture/startRecording.png'),
  onRecording: require('../assets/picture/onRecording.png'),
  festBookLogo: require('../assets/picture/FestbookLogo.png'),
  galleryIcon: require('../assets/picture/gallery.png'),
  videoMode: require('../assets/picture/videoMode.png'),
  pictureMode: require('../assets/picture/pictureMode.png'),
  pictureModeDark: require('../assets/picture/pictureModeDark.png'),
  videoModeDark: require('../assets/picture/videoModeDark.png'),
  successIcon: require('../assets/picture/success.png'),
  arrowBack: require('../assets/picture/arrowBack.png'),
  accept: require('../assets/picture/accept.png'),
  close: require('../assets/picture/close.png'),
  play: require('../assets/picture/play.png'),
  pause: require('../assets/picture/pause.png'),
  exit: require('../assets/picture/exit.png'),
  pauseVideo: require('../assets/picture/pauseVideo.png'),
  playVideo: require('../assets/picture/playVideo.png'),
};
